[package]
name = "bevy_image_export"
version = "0.4.0"
edition = "2021"
categories = ["graphics", "rendering"]
keywords = ["creative", "coding", "sketching"]
description = "Bevy plugin for rendering image sequences"
documentation = "https://docs.rs/bevy_image_export"
license = "MIT"
readme = "README.md"
repository = "https://github.com/paulkre/bevy_image_export"

[dependencies]
bevy = { version = "0.10", default-features = false, features = [
  "bevy_render",
  "bevy_asset",
] }
futures = "0.3"
futures-lite = "1"
image = "0.24"
wgpu = "0.15"

[dev-dependencies]
bevy = { version = "0.10", default-features = false, features = [
  "bevy_sprite",
  "bevy_winit",
  "bevy_core_pipeline",
  "bevy_pbr",
] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
