[package]
name = "bevy_image_export"
version = "0.4.0"
edition = "2021"
categories = ["graphics", "rendering"]
keywords = ["creative", "coding", "sketching"]
description = "Bevy plugin for rendering image sequences"
documentation = "https://docs.rs/bevy_image_export"
license = "MIT"
readme = "README.md"
repository = "https://github.com/paulkre/bevy_image_export"

[dependencies]
bevy = "0.10"
futures = "0.3"
futures-lite = "1"
image = "0.24"
wgpu = "0.15"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
