[package]
name = "bevy_image_export"
version = "0.1.0"
edition = "2021"
categories = ["graphics", "rendering"]
description = "Bevy plugin for exporting your app as an image sequence"
license = "MIT"
readme = "README.md"
repository = "https://github.com/paulkre/bevy_image_export"

[dependencies]
bevy = "0.8"
futures = "0.3"
futures-lite = "1"
image = ">=0.24"
wgpu = ">=0.12"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
